### ISSUE TITLE
sign up issue

### ISSUE THREAD

**Issue by WendyOWilliams** [p0p1t0/Spoofer#1]
I'm interested. Before signing up would like to test - any chance to get 2 credits for a test or request you to run a test from a specific email account, that doesn't have dmarc implemented of course?

**Comment by p0p1t0** [comment]
El 2023-12-25 23:12, WendyOWilliams escribió:

> I'm interested. Before signing up would like to test - any chance to 
> get 2 credits for a test or request you to run a test from a specific 
> email account, that doesn't have dmarc implemented of course?

Hello, actually Im not at home, when I arrive I will prepare a pincode 
with 2 free uses for test

https://t.me/p0p1t0tools
--=_28c735b21f793e63478d01a1c233d907
Content-Transfer-Encoding: quoted-printable
Content-Type: text/html; charset=UTF-8

<html><head><meta http-equiv=3D"Content-Type" content=3D"text/html; charset=
=3DUTF-8" /></head><body style=3D'font-size: 10pt; font-family: Verdana,Gen=
eva,sans-serif'>
<p id=3D"reply-intro">El 2023-12-25 23:12, WendyOWilliams escribi&oacute;:<=
/p>
<blockquote type=3D"cite" style=3D"padding: 0 0.4em; border-left: #1010ff 2=
px solid; margin: 0">
<div class=3D"pre" style=3D"margin: 0; padding: 0; font-family: monospace">=
I'm interested. Before signing up would like to test - any chance to get 2 =
credits for a test or request you to run a test from a specific email accou=
nt, that doesn't have dmarc implemented of course? &nbsp;</div>
</blockquote>
<p><br /></p>
<p>Hello, actually Im not at home, when I arrive I will prepare a pincode w=
ith 2 free uses for test</p>
<p><br /></p>
<p>https://t.me/p0p1t0tools</p>

</body></html>

--=_28c735b21f793e63478d01a1c233d907--

**Comment by WendyOWilliams** [comment]
@p0p1t0 thanks. feel free to DM them to me or just reply with pin to the email address through which I sent you email yesterday.

**Comment by p0p1t0** [comment]
Hello, thanks for getting in touch. Talk to me on my Instagram so we can 
have a more fluid conversation: https://t.me/p0p1t0tools
